// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"fmt"
	"sync"

	"github.com/openai/openai-go"
	"github.com/pingcap/tidb/tests/llmtest/testcase"
)

// GeneratorKind defines the output type of a generator.
type GeneratorKind int

const (
	GeneratorKindTestcase GeneratorKind = iota
	GeneratorKindBugSeed
)

// PromptGenerator is the interface for prompt generator.
//
// `count` in GeneratePrompt is only meaningful for generators that accumulate cases until they reach a target count.
// One-shot generators ignore it and return all items for the group in a single prompt.
type PromptGenerator[T any] interface {
	Name() string
	Kind() GeneratorKind
	// OneShotPerGroup reports whether the generator should issue exactly one prompt per group and let that prompt decide the final fan-out.
	OneShotPerGroup() bool
	Groups() []string

	GeneratePrompt(group string, count int, existCases []T) []openai.ChatCompletionMessageParamUnion
	Unmarshal(response string) []T
}

// Store persists items generated by the prompt generators.
type Store[T any] interface {
	Exist(group string) []T
	Append(group string, item T)
	Save() error
}

type storeFactory[T any] func(name string) (Store[T], error)

// Runner executes a generator without exposing its concrete output type.
type Runner interface {
	Name() string
	Kind() GeneratorKind
	Groups() []string
	Validate() error
	Run(openAIToken string, openAIBaseURL string, modelName string, testCount int, parallelism int) error
}

// preRunValidator allows generators with external dependencies to reject a run
// before worker goroutines start.
type preRunValidator interface {
	Validate() error
}

type generatorEntry[T any] struct {
	name    string
	kind    GeneratorKind
	factory storeFactory[T]
	newGen  func() (PromptGenerator[T], error)

	once sync.Once
	gen  PromptGenerator[T]
	err  error
}

// Name implements Runner.Name.
func (e *generatorEntry[T]) Name() string {
	return e.name
}

// Kind implements Runner.Kind.
func (e *generatorEntry[T]) Kind() GeneratorKind {
	return e.kind
}

// Groups implements Runner.Groups.
func (e *generatorEntry[T]) Groups() []string {
	gen, err := e.load()
	if err != nil || gen == nil {
		return nil
	}
	return gen.Groups()
}

// Validate implements Runner.Validate.
func (e *generatorEntry[T]) Validate() error {
	gen, err := e.load()
	if err != nil {
		return err
	}
	if validator, ok := any(gen).(preRunValidator); ok {
		return validator.Validate()
	}
	return nil
}

// Run implements Runner.Run.
func (e *generatorEntry[T]) Run(openAIToken string, openAIBaseURL string, modelName string, testCount int, parallelism int) error {
	if err := e.Validate(); err != nil {
		return err
	}

	gen, err := e.load()
	if err != nil {
		return err
	}
	if gen == nil {
		return fmt.Errorf("generator %s unavailable", e.name)
	}
	store, err := e.factory(e.name)
	if err != nil {
		return err
	}
	generator := New(
		store, parallelism,
		openAIToken, openAIBaseURL, modelName, gen, testCount,
	)
	generator.Run()
	generator.Wait()
	return store.Save()
}

// load loads the generator.
func (e *generatorEntry[T]) load() (PromptGenerator[T], error) {
	e.once.Do(func() {
		e.gen, e.err = e.newGen()
	})
	return e.gen, e.err
}

// generators is a map from generator name to generator.
var generators map[string]Runner

// AllTestcaseGenerators returns all the registered generators.
func AllTestcaseGenerators() []Runner {
	result := make([]Runner, 0, len(generators))
	for _, g := range generators {
		if g.Kind() != GeneratorKindTestcase {
			continue
		}
		result = append(result, g)
	}
	return result
}

// GetPromptGenerator returns the generator by name.
func GetPromptGenerator(name string) Runner {
	return generators[name]
}

func registerGenerator[T any](name string, kind GeneratorKind, newGen func() (PromptGenerator[T], error), factory storeFactory[T]) {
	if generators == nil {
		generators = make(map[string]Runner)
	}
	generators[name] = &generatorEntry[T]{
		name:    name,
		kind:    kind,
		factory: factory,
		newGen:  newGen,
	}
}

func testcaseStore(name string) (Store[*testcase.Case], error) {
	return testcase.Open(fmt.Sprintf("testdata/%s.json", name))
}

func bugSeedStore(name string) (Store[*BugSeed], error) {
	return OpenBugSeedStore(fmt.Sprintf("testdata/%s.json", name))
}

func oracleStore(name string) (Store[*OracleCase], error) {
	return OpenOracleStore(fmt.Sprintf("testdata/%s.json", name))
}
